# Don't print a new line at the start of the prompt
add_newline = false



format = """\
        $time\
        $username\
        $hostname\
        $directory\
        $aws\
        $gcloud\
        $singularity\
        $kubernetes\
        $docker_context\
        (â†“ Source control - for right side â†“)\
        $hg_branch\
        $git_branch\
        $git_commit\
        $git_status\
        $git_state\
        (â†‘ Source control - for right side â†‘)\
        (â†“ Toolchain version modules â†“)\
        $crystal\
        $dart\
        $dotnet\
        $elixir\
        $elm\
        $erlang\
        $golang\
        $java\
        $julia\
        $nim\
        $nodejs\
        $ocaml\
        $perl\
        $php\
        $purescript\
        $python\
        $ruby\
        $rust\
        $swift\
        $terraform\
        $zig\
        (â†‘ Toolchain version modules â†‘)\
        (â†“ Package modules â†“)\
        $helm\
        $package\
        $cmake\
        $conda\
        (â†‘ Package modules â†‘)\
        $nix_shell\
        $memory_usage\
        $env_var\
        $custom\
        (â†‘ above input line â†‘)\
        $line_break\
        (â†“ on input line â†“)\
        $battery\
        $shlvl\
        $jobs\
        $cmd_duration\
        $status\
        $character\
    """

# Generic prompt configurations
[character]
success_symbol = "[ï—š](bold green)[ï—š](bold yellow)[ï—š](bold red)[ï—š](bold purple)"
error_symbol = "[ï—š](bold green)[ï—š](bold yellow)[ï—š](bold red)[ï—š](bold purple)"
vicmd_symbol = "[ï—š](bold green)[ï—š](bold yellow)[ï—š](bold red)[ï—š](bold purple)"
format = "$symbol "

[line_break]
disabled = false


#[character]                            # The name of the module we are configuring is "character"
#success_symbol = "[ï—š](bold green)[ï—š](bold yellow)[ï—š](bold red)[ï—š](bold purple)"     # The "success_symbol" segment is being set to "âœ" with the color "bold green"

#error_symbol = "[âœ—](bold red) "
# Disable the package module, hiding it from the prompt completely
#format = "$symbol "

# Module configurations


[aws]
# disabled = true
symbol = "îŒ½ "
style = ""
format = '[$symbol$profile(\($region\))]($style)'

[battery]
# disabled = true
full_symbol = "ï•¸"
charging_symbol = "ï–‡ "
discharging_symbol = "ï–Œ "
unknown_symbol = "ï–"
empty_symbol = "ï–"
format = "[$symbol$percentage]($style)"
[[battery.display]]
threshold = 10
style = "bold fg:#EEEEEE"
[[battery.display]]
threshold = 20
style = ""

[cmake]
# disabled = true
# symbol = "ï¨µ" # alternate
symbol = "ï¨¶"
style = ""
format = "[$symbol$version]($style)"

[cmd_duration]
# disabled = true
style = ""
min_time = 2_000
show_milliseconds = true
show_notifications = false
min_time_to_notify = 45_000
format = "[ ï¨š$duration]($style)"

[conda]
# disabled = true
symbol = "ï„Œ "
style = ""
ignore_base = true
truncation_length = 1
format = "[(fg:#464347)$symbol$environment]($style)"

[crystal]
# disabled = true
symbol = "ïˆ™ "
style = ""
format = "[$symbol$version(fg:#EEEEEE)]($style)"

[dart]
# disabled = true
symbol = "î˜ " # original
# symbol = "ï¯‘ " # clearer
style = ""
format = "[$symbol$version]($style)"

[directory]
style = "italic fg:#EEEEEE"
read_only = "ï ½"
read_only_style = ""
truncation_length = 4
truncate_to_repo = true
# truncation_symbol = "â€¦"
# fish_style_pwd_dir_length = 3
format = "([$read_only]($read_only_style))[$path]($style)"

[directory.substitutions]
"~/Documents" = "ïœ™"
"~/Music" = "ï¢ƒ"
"~/Movies" = "ï—¼"
"~/Pictures" = "ï›"
"~/Sources" = "ï„¡"
"~" = "ï‘­ "
"/" = " î‚± "

[docker_context]
# disabled = true
symbol = "ïŒˆ "
style = ""
only_with_files = true
format = "[$symbol$context]($style)"

[dotnet]
# disabled = true
symbol = "î¿ "
style = ""
heuristic = true
format = "[$symbol$version( ï§½$tfm)]($style)"

[elixir]
# disabled = true
symbol = "î˜­ "
style = ""
format = '[$symbol$version \(OTP:$otp_version\)]($style)'

[elm]
# disabled = true
symbol = "î˜¬ " # original
# symbol = "îˆœ " # clearer
style = ""
format = "[$symbol$version]($style)"

[env_var]
disabled = true
symbol = "î• "
style = ""
variable = "0"
default = "fish"
format = "([$symbol$env_value]($style))"

[erlang]
# disabled = true
symbol = "î± "
style = ""
format = "[$symbol$version]($style)"

[gcloud]
# disabled = true
symbol = "â˜ï¸ "
style = ""
format = '[$symbol$account(\($region\))]($style)'

[git_branch]
# disabled = true
symbol = "ï¡ "
# symbol = "ï˜ " # alternate
style = ""
# truncation_length = 4
# truncation_symbol = ""
format = "[$symbol$branch]($style)"

[git_commit]
# disabled = true
style = ""
commit_hash_length = 4
# only_detached = true
format = "[#$hash]($style)"

[git_state]
# disabled = true
style = ""
rebase = "rebasing"
merge = "merging"
revert = "reverting"
cherry_pick = "îŠ› picking"
bisect = "bisecting"
am = "am'ing"
am_or_rebase = "am/rebase"
format = '\([$state($progress_current/$progress_total)]($style)\)'

[git_status]
# disabled = true
style = ""
stashed = "ï€œ ${count}"
ahead = "ï²— ${count}"
behind = "ï²” ${count}"
diverged = "ï§¡ ${ahead_count} ${behind_count}"
conflicted = "ï€¤${count}"
deleted = " ï€${count}"
renamed = "ï«¦${count}"
modified = " ï¥”${count}"
staged = " ï€Œ ${count}"
untracked = " ï ${count}"
format = "([$stashed$staged$modified$renamed$untracked$deleted$conflicted$ahead_behind]($style))"

[golang]
# disabled = true
symbol = "î˜§ "
style = ""
format = "[$symbol$version]($style)"

[helm]
# disabled = true
symbol = "ï´± "
style = ""
format = "[$symbol$version]($style)"

[hostname]
# disabled = true
style = ""
# ssh_only = false
trim_at = "."
format = "[($style)$hostname]($style)"

[java]
# disabled = true
symbol = "î‰– "
style = ""
format = "[$symbol$version]($style)"

[jobs]
# disabled = true
symbol = " ï€º "
style = "bold fg:#FFA200"
# threshold = 1
format = "[$symbol$number]($style)"

[julia]
# disabled = true
symbol = "î˜¤ "
style = ""
format = "[$symbol$version]($style)"

[kubernetes]
disabled = false
symbol = "â˜¸ï¸"
style = ""
format = '[$symbol$context(\($namespace\))]($style)'

[memory_usage]
# disabled = false
symbol = "ï¡š "
style = ""
threshold = 75
format = "([$symbol$ram(:$swap)]($style))"

# Mercurial
[hg_branch]
disabled = false
symbol = "î‚  "
style = ""
# truncation_length = 8 # default = 2^63 - 1
# truncation_symbol = "â€¦"
format = "[$symbol$branch]($style)"

[nim]
# disabled = true
symbol = "î‰® "
style = ""
format = "[$symbol$version]($style)"

[nix_shell]
# disabled = true
symbol = "ïŒ“ "
style = ""
impure_msg = '[\(impure\)]'
pure_msg = '[\(pure\)]'
format = '[$symbol$name$state]($style)'

[nodejs]
# disabled = true
symbol = "ï¢˜ "
style = ""
format = "[$symbol$version]($style)"

[ocaml]
# disabled = true
symbol = "ğŸ« "
style = ""
format = "[$symbol$version]($style)"

[package]
# disabled = true
symbol = "ï’‡ "
style = ""
display_private = false
format = "[$symbol$version]($style)"

[perl]
# disabled = true
symbol = "ğŸª "
style = ""
format = "[$symbol$version]($style)"

[php]
# disabled = true
symbol = "î˜ˆ "
style = ""
format = "[$symbol$version]($style)"

[purescript]
# disabled = true
symbol = "<=>"
style = ""
format = "[$symbol$version]($style)"

[python]
# disabled = true
symbol = "î˜† "
style = ""
# pyenv_version_name = true
pyenv_prefix = "pyenv "
python_binary = "python3"
format = '[$symbol$pyenv_prefix$version(\($virtualenv\))]($style)'

[ruby]
# disabled = true
symbol = "ï» "
# symbol = "îˆ¾ " # alternate
style = ""
format = "[$symbol$version]($style)"

[rust]
# disabled = true
symbol = "î¨ "
# symbol = "ï€“ " # alternate
style = ""
format = "[$symbol$version(]($style)"

[shlvl]
# disabled = false
symbol = "ï…ˆ"
style = "bold fg:#FBDE2D"
threshold = 2
format = "[$symbol$shlvl]($style)"

[singularity]
# disabled = true
symbol = "î‚·Sî‚µ"
style = ""
format = '[$symbol\[$env\]]($style)'

[swift]
# disabled = true
symbol = "ï¯£ "
style = ""
format = "[$symbol$version]($style)"

[status]
# disabled = false
symbol = "ï„ª"
style = ""
format = "[$symbol$status]($style)"

[terraform]
disabled = false
symbol = "ï¨ˆ"
style = ""
format = '[$symbol\($workspace\)]($style)'
### uncomment the following, to see the version
# format = "[$symbol$version($workspace)]($style)"


[username]
 disabled = false
# show_always = true
style_root = "bold fg:#FF5511"
style_user = ""
format = "[$user]($style)"

[zig]
# disabled = true
symbol = "ï¼»Zï¼½"
# symbol = "â†¯ " # alternate
style = ""
format = "[$symbol$version]($style)"
#EOF.
